### PR TITLE
build diff

### PR DESCRIPTION
**Pull request by brad-decker**
## ethjs-query

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/ethjs/ethjs-query/blob/master/.github/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/ethjs/ethjs-query/blob/master/.github/CONTRIBUTING.md)
- [ ] Pull request has tests (we are going for 100% coverage!)
- [x] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/ethjs/ethjs-query/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by brad-decker** [comment]
@legobeat could you investigate this when you get a chance?

**Comment by brad-decker** [comment]
Screenshot 2023-09-20 at 3 35 04 PM

**Comment by pedronfigueiredo** [comment]
I also get diffs on the `package-lock.json` when I use the versions you indicated above Brad.

**Comment by brad-decker** [comment]
@legobeat i think it may be Operating system differences in how npm is resolving packages at this version of npm? https://stackoverflow.com/questions/45335169/why-do-i-get-vastly-different-package-lock-json-files-when-i-run-npm-install -- i can remove the package-lock changes but I cannot build the package to publish without them.

**Pull request merged**
